version: '3.5'
services:
  web:
    #image: 127.0.0.1:5000/natomas-web
    ports:
      - 8000:8000
    secrets:
      - client-secret
      - secret-key
    environment:
      - DEBUG=True
      - OAUTHLIB_INSECURE_TRANSPORT=1
    command: gunicorn -b 0.0.0.1:8000 application:application
    # Infinite loop, to keep it alive, for debugging
    # command: bash -c "while true; do echo 'sleeping...' && sleep 10; done"

secrets:
  client-secret:
    external: true
  secret-key:
    external: true
